services:
  couchdb:
    build:
      context: .
      dockerfile_inline: |
        FROM couchdb:latest
        COPY ./couchdb/local.ini /opt/couchdb/etc
    container_name: couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=$COUCHDB_USER
      - COUCHDB_PASSWORD=$COUCHDB_PASSWORD
    volumes:
      - ./couchdb:/opt/couchdb/data
  nginx:
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:latest
        WORKDIR /etc/nginx
        # COPY certificate.crt ssl/
        # COPY private.key ssl/
    container_name: nginx
    restart: unless-stopped
    # ports: [80:80,443:443]
    ports: [80:80]
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  nodejs:
    build:
      context: .
      dockerfile_inline: |
        FROM node:latest
        WORKDIR /usr/src/app/
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - ./nodejs:/usr/src/app
    command: >
      sh -c "npm install &&
             npm start"
    ports:
      - "8080:8080"