services:
  couchdb:
    build:
      context: .
      dockerfile_inline: |
        FROM couchdb:latest
        COPY ./couchdb/local.ini /opt/couchdb/etc
    container_name: couchdb
    restart: unless-stopped
    ports:
      - "${COUCHBD_PORT}:${COUCHBD_PORT}"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - ./couchdb:/opt/couchdb/data
  nginx:
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:latest
        WORKDIR /etc/nginx
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  nodejs:
    build:
      context: ./nodejs
      dockerfile_inline: |
        FROM node:slim
        WORKDIR /usr/src/app/
        COPY ./ ./
        RUN npm install && npm cache clean --force
    container_name: nodejs
    restart: unless-stopped
    command: >
      sh -c "npm start"
    ports:
      - "8080:8080"
